id = "yara"
name = "Yara"
version = "0.0.4"
schema_version = 1
authors = ["egibs <evan@egibs.xyz>", "Joakim Kennedy <joakim@intezer.com>"]
description = "Yara syntax highlighting for Zed."
repository = "https://github.com/egibs/yara.zed"

[grammars.yara]
repository = "https://github.com/celstur/tree-sitter-yara.git"
commit = "b49d980b2e111e0b09a6a8bae18b3fa2b6cf4797"

[language_servers.yr-ls]
name = "yr-ls"
languages = ["Yara"]
